### ISSUE TITLE
Original license

### ISSUE THREAD

**Issue by DenHeadless** [anodamobi/ANStorage#3]
Can i ask you to restore original MIT license in project headers, that were not changed much?

As said in MIT license, it's *only* requirement is: 
```
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
```
[MIT license](http://choosealicense.com/licenses/mit/)

This also concerns [ANCollectonController](https://github.com/anodamobi/ANCollectonController) and [ANTableController](https://github.com/anodamobi/ANTableController) - in places, where code change is not significant.

**Comment by oks** [comment]
Please check, in ANCollectionController all licenses are untouched, in ANTableController almost all classes were updated.
 Also please notice, that both of repos from this moment are unsupported and will be removed.
If you have any questions about licenses and your rights please email - info@anoda.mobi and get reply. 
Thanks.
